name: carnd-term1
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.9.12
    - pip==24.2
    - pip:
        - tensorflow[and-cuda]==2.17.0
        - numpy==1.26.4
        - h5py==3.12.1
        - requests==2.32.3
        - PySide6==6.8.0.1
        - opencv-python==4.10.0.84
        - moviepy==1.0.3
        - matplotlib==3.9.2
        - pillow==11.0.0
        - scikit-learn==1.5.2
        - scikit-image==0.24.0
        - scipy==1.13.1
        - eventlet==0.37.0
        - flask-socketio==5.4.1
        - seaborn==0.13.2
        - pandas==2.2.3
        - ffmpeg==1.4
        - imageio==2.36.0
        - jupyter
